const RADIO_VALUE_DATE = 'date';
const RADIO_VALUE_TODAY = 'today';
const RADIO_VALUE_OFFSET = 'offset';

const ERROR_INVALID_DATE_FIELD = 'ERROR_INVALID_DATE_FIELD';
const ERROR_INVALID_OFFSET = 'ERROR_INVALID_OFFSET';

export {
  RADIO_VALUE_DATE,
  RADIO_VALUE_TODAY,
  RADIO_VALUE_OFFSET,
  ERROR_INVALID_DATE_FIELD,
  ERROR_INVALID_OFFSET
};
